# Generated by Django 3.0.4 on 2020-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(max_length=100)),
                ('news_date', models.DateTimeField()),
                ('news_image', models.TextField()),
                ('news_text', models.TextField()),
            ],
        ),
    ]
