# Generated by Django 3.0.4 on 2020-03-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'One News', 'verbose_name_plural': 'News'},
        ),
    ]
