# Generated by Django 3.0.4 on 2020-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200323_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images'),
        ),
    ]
