# Generated by Django 3.0.4 on 2020-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_contest_feedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='сontest_files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
