# Generated by Django 3.0.4 on 2020-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_contest_сontest_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='сontest_files',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
