# Generated by Django 3.0.4 on 2020-03-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200324_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='ClassImage',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='ClassNews',
        ),
        migrations.RemoveField(
            model_name='feedfile',
            name='feed',
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.AlterModelOptions(
            name='classnews',
            options={'verbose_name': 'One_News', 'verbose_name_plural': 'News'},
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='FeedFile',
        ),
    ]
