# Generated by Django 3.0.4 on 2020-03-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200324_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnews',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
