# Generated by Django 3.0.4 on 2020-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200324_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnews',
            name='news_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
