# Generated by Django 3.0.4 on 2020-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200324_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='images'),
        ),
    ]
