# Generated by Django 3.0.4 on 2020-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(blank=True, max_length=100, null=True)),
                ('gallery_image', models.TextField(blank=True, null=True)),
                ('gallery_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
            },
        ),
    ]
