# Generated by Django 3.0.4 on 2020-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcontest',
            options={'verbose_name': 'Contest', 'verbose_name_plural': 'Contests'},
        ),
        migrations.AlterModelOptions(
            name='classfile',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='classcontest',
            name='сontest_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
