# Generated by Django 3.0.4 on 2020-03-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200324_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classcontest',
            old_name='сontest_date',
            new_name='contest_date',
        ),
        migrations.RenameField(
            model_name='classcontest',
            old_name='сontest_image',
            new_name='contest_image',
        ),
        migrations.RenameField(
            model_name='classcontest',
            old_name='сontest_text',
            new_name='contest_text',
        ),
        migrations.RenameField(
            model_name='classcontest',
            old_name='сontest_title',
            new_name='contest_title',
        ),
    ]
